quick entity selection using right MB click
thm-mnd-ii/eWiLL pull request #236
Opened 2023-10-15 21:42 UTC by ymll58

Solves #215

2023-10-16 08:38 UTC, Medienkunzt requested changes
Referring to ticket #215 , the context menu was not built in the given structure (use vuetify components). This structure is important, because further issues will be based upon.

When inserting the elements, the new entity is not inserted in the correct position. The new element should be inserted exactly at the position of the mouse click.

2023-10-16 08:38 UTC, Medienkunzt commented on modules/core/web/src/components/ModelingTool.vue
> +const contextMenuPosition = ref({ x: '0px', y: '0px' });
Variables should never be defined under the imports. Please place them between the props and onMounted().

2023-10-16 08:38 UTC, Medienkunzt commented on modules/core/web/src/components/ModelingTool.vue
> +  isContextMenuVisible.value = false;
pls remove unused functions

2023-10-16 08:38 UTC, Medienkunzt commented on modules/core/web/src/components/ModelingTool.vue
> +}
if the vue components are used it could be possible that this is no longer needed.

2023-10-19 07:53 UTC, Medienkunzt requested changes
If you want to edit an entity with a right click, for example to add attributes, then the field for the quick insertion of elements also appears.
![image](https://github.com/thm-mnd-ii/eWiLL/assets/57532417/05c87ffb-449c-47ec-9d3f-a4269d599bd4)

2023-10-19 08:02 UTC, Medienkunzt requested changes
The context menu is still not in the given structure. See figure in ticket...
![image](https://github.com/thm-mnd-ii/eWiLL/assets/57532417/8a61272b-ec51-451a-8a5c-a544289da36e)

2023-10-19 12:09 UTC, ymll58 commented
All the above mentionned requests were implemented . 
the quick insertion menu will not appear as long as the user clicks accurately  on the frame of the entities. 
double clicks on the frame will still activate the quick menu . 
![image](https://github.com/thm-mnd-ii/eWiLL/assets/57532417/05c87ffb-449c-47ec-9d3f-a4269d599bd4)

2023-10-19 16:16 UTC, Medienkunzt requested changes
I've made several adjustments to ensure that all functionalities are represented as described in the ticket.

However, there's one more thing that needs to be addressed. As seen throughout the project, we're working in a component-based manner. To clearly represent the "quick insert" functionality, it should be refactored into its own component, just like all other functions. Please take into account the communication capabilities provided by Vue3 between components when doing this.

2023-11-23 08:39 UTC, Medienkunzt approved these changes

2023-11-23 08:41 UTC, merged